// Generated by CoffeeScript 1.4.0
(function() {
  var app, express;

  express = require("express");

  app = express();

  app.configure(function() {
    app.set("views", __dirname + "/views");
    app.set("view engine", "ejs");
    app.use(express.bodyParser());
    return app.use(express.methodOverride());
  });

  app.use(app.router);

  app.use(express["static"](__dirname + "/public"));

  app.get("/", function(req, res) {
    return res.render("index", {
      title: "Express"
    });
  });

  app.listen(3000);

  console.log("Express server listening on port 3000");

}).call(this);
